source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

target 'NVMImageMaker_Example' do
  pod "NVMImageMaker", :path => "../"

  target 'NVMImageMaker_Tests' do
    inherit! :search_paths
    pod "FBSnapshotTestCase/Core"
  end
end
